# Site settings

title: Phase Field Models of Ternary Eutectoid Alloys
header-img: img/home-bg.jpg
email: aiskakov3@gatech.edu
description: "Process-Structure Linkage of Ternary Eutectoid Al Alloy"
baseurl: "/project8883"
url: "http://aiskakov.github.io"
github_username:  aiskakov
project_repository: project8883

# Build settings
# Don't change these variables
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
